"""empty message

Revision ID: 93d793e9cb74
Revises: 17c7b4e8abaa
Create Date: 2019-03-14 18:17:36.567384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93d793e9cb74'
down_revision = '17c7b4e8abaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=260),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email_confirmed_at')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('email_confirmed_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=260),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
